---
sudo: false
language: c
matrix:
  include:
    - env: TEST=markdownlint
      services:
        - docker
      script: ./tests/mdl.sh

    - env: TEST=terraform
      services:
        - docker
      script: cd tf; ../tests/terraform.sh

    - env: TEST=yamllint
      services:
        - docker
      script: ./tests/yamllint.sh

    - env: TEST=shellcheck
      services:
        - docker
      script: ./tests/shellcheck.sh

    # check manifests only
    - env: TEST=puppet-lint
      language: ruby
      rvm: '2.5'
      script: bundle exec rake puppet_lint

    - env: TEST=librarian-puppet
      language: ruby
      rvm: '2.5'
      script: bundle exec rake librarian

    - env: TEST="jenknis_demo (puppet module)"
      language: ruby
      rvm: '2.5'
      # WHY IS TRAVIS SETTING BUNDLE_GEMFILE? ARGH!
      before_install: unset BUNDLE_GEMFILE && cd jenkins_demo
      install: bundle install --jobs=3 --retry=3 --frozen
      script: bundle exec rake

    - env: TEST=rubocop
      language: ruby
      rvm: '2.5'
      script: bundle install && bundle exec rubocop

    - env:
        - TEST=make
        - TF_VAR_env_name=testenv
        - TF_VAR_service_name=testsvc
        - TF_VAR_domain_name=example.com
        - AWS_DEFAULT_REGION=us-east-1
      script: ./tests/make.sh

    - env: TEST=jsonlint
      services:
        - docker
      script: ./tests/jsonlint.sh
branches:
  only:
    - master
    # also matched against tag pushes
    - /^\d+\.\d+\.\d+$/
notifications:
  email: false
