---
prometheus:
  ingress:
    enabled: true
    hosts:
      - ${prometheus_fqdn}
    tls:
      - secretName: prometheus-server-tls
        hosts:
          - ${prometheus_fqdn}
grafana:
  ingress:
    enabled: true
    hosts:
      - ${grafana_fqdn}
    tls:
      - secretName: prometheus-server-tls
        hosts:
          - ${grafana_fqdn}
